//
// Created by Shuhao Zhang on 19/07/2021.
//

#ifndef SESAME_INCLUDE_UTILS_STACKTRACELOADER_HPP_
#define SESAME_INCLUDE_UTILS_STACKTRACELOADER_HPP_

void collectAndPrintStacktrace();

#endif //SESAME_INCLUDE_UTILS_STACKTRACELOADER_HPP_
