//
// Created by Shuhao Zhang on 9/6/21.
//

#ifndef ONLINEMLBENCHMARK_SRC_OUTLIERDETECTION_OUTLIERDETECTION_HPP_
#define ONLINEMLBENCHMARK_SRC_OUTLIERDETECTION_OUTLIERDETECTION_HPP_

class OutlierDetection {};

#endif // ONLINEMLBENCHMARK_SRC_OUTLIERDETECTION_OUTLIERDETECTION_HPP_
