//
// Created by Shuhao Zhang on 9/6/21.
//

#ifndef ONLINEMLBENCHMARK_SRC_SUMMARIZATION_SUMMARIZATION_HPP_
#define ONLINEMLBENCHMARK_SRC_SUMMARIZATION_SUMMARIZATION_HPP_

class Summarization {

};

#endif // ONLINEMLBENCHMARK_SRC_SUMMARIZATION_SUMMARIZATION_HPP_
