//
// Created by Shuhao Zhang on 19/07/2021.
//

#ifndef SESAME_INCLUDE_ALGORITHM_DATASTRUCTURE_DATASTRUCTURE_HPP_
#define SESAME_INCLUDE_ALGORITHM_DATASTRUCTURE_DATASTRUCTURE_HPP_

#endif //SESAME_INCLUDE_ALGORITHM_DATASTRUCTURE_DATASTRUCTURE_HPP_
