//
// Created by Shuhao Zhang on 9/6/21.
//

#ifndef ONLINEMLBENCHMARK_SRC_WINDOWMODEL_WINDOWMODEL_HPP_
#define ONLINEMLBENCHMARK_SRC_WINDOWMODEL_WINDOWMODEL_HPP_

class WindowModel {

};

#endif // ONLINEMLBENCHMARK_SRC_WINDOWMODEL_WINDOWMODEL_HPP_
