//
// Created by Shuhao Zhang on 9/6/21.
//

#ifndef ONLINEMLBENCHMARK_SRC_OFFLINECLUSTERING_KMEANS_HPP_
#define ONLINEMLBENCHMARK_SRC_OFFLINECLUSTERING_KMEANS_HPP_

#include "OfflineClustering.hpp"

class KMeans : OfflineClustering {};

#endif // ONLINEMLBENCHMARK_SRC_OFFLINECLUSTERING_KMEANS_HPP_
