//
// Created by Shuhao Zhang on 9/6/21.
//

#ifndef ONLINEMLBENCHMARK_SRC_DATASTRUCTURE_DATASTRUCTURE_HPP_
#define ONLINEMLBENCHMARK_SRC_DATASTRUCTURE_DATASTRUCTURE_HPP_

class DataStructure {};

#endif // ONLINEMLBENCHMARK_SRC_DATASTRUCTURE_DATASTRUCTURE_HPP_
