name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'include'
          - 'src'
          - 'benchmark/src'
          - 'test'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.10.1
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}